Merge recent package installer changes from my branch in to trunk. Includes updates to Credits, installation log messages and localizable strings. Check for existence of EFI system partition before running the check for previous Chameleon installations. Only backup /Extra folder if necessary when running upgrade install.
git-svn-id: http://forge.voodooprojects.org/svn/chameleon/trunk@1753 b5af796a-00a8-11df-919b-ffff7a100b7d

diff --git a/package/Scripts/Main/Standardpostinstall b/package/Scripts/Main/Standardpostinstall
--- a/package/Scripts/Main/Standardpostinstall
+++ b/package/Scripts/Main/Standardpostinstall
@@ -56,6 +56,7 @@ targetSlice=${targetDevice#*disk*s}
 targetResources="${targetVolume}/usr/local/bin/"
 
 updateStage1=1 # by default update partition boot sector
+efiPartitionExist=0 # target volume does not have EFI system partition.
 
 echo "==============================================="
 echo "DEBUG: display script variables"
@@ -82,12 +83,17 @@ echo ""
 "$scriptDir"InstallLog.sh "${targetVolume}" "Target volume = ${targetVolume} on ${targetDevice}"
 
 # Double check we can see the selected partition and it's of the right type.
-# If the following script finds anything, it returns 1 to indicate failure.
+# The following script returns either 0 or 1 to proceed, or 2 to indicate failure.
 
 "$scriptDir"CheckProceed.sh "${targetVolume}" "${targetDevice}" "${targetVolume}" "${scriptDir}"
 returnValue=$?
-if [ ${returnValue} = 0 ]; then
+if [ ${returnValue} -ne 2 ]; then
 	# OK to proceed
+	
+	# Remember if the target volume has an EFI system partition.
+	if [ ${returnValue} -ne 1 ]; then
+		efiPartitionExist=1
+	fi
 
 	# Does a GRUB or Linux loader already exist in the disk's MBR?
 	# The script returns 1 if yes, 0 if no.
@@ -162,32 +168,21 @@ if [ ${returnValue} = 0 ]; then
 		# Write the stage 2 loader to the root of the selected partition
 		"$scriptDir"WriteChameleonStage2.sh "${stage2Loader}" "${3}" "${targetDevice}" "${targetVolume}" "${scriptDir}"
 
-
 		# Next we look to check for existing Chameleon installations.
-		# But as it will check /Volumes/EFI for the stage 2 loader,
-		# we need to make sure it's mounted.
-
-		# Tell the user what's going on.
 		"$scriptDir"InstallLog.sh "${targetVolume}" "LineBreak"
-		"$scriptDir"InstallLog.sh "${targetVolume}" "About to check your disk for previous installations"
-		"$scriptDir"InstallLog.sh "${targetVolume}" "which involves checking the EFI system partition if"
-		"$scriptDir"InstallLog.sh "${targetVolume}" "appropriate for this disk."
-
-		# Unmount ALL mounted volumes named EFI.
-		# Returns 0=success, 1=fail
-		"$scriptDir"UnMountEFIvolumes.sh "${targetVolume}" "${scriptDir}"
-		returnValue=$?
-		if [ ${returnValue} = 0 ]; then
-			# OK to proceed
-
-			if [ ${partitionScheme} = 1 ] || [ ${partitionScheme} = 2 ]; then
+		"$scriptDir"InstallLog.sh "${targetVolume}" "Preparing to check target disk for previous installations."
+		if [ ${efiPartitionExist} -ne 0 ]; then # volume has an EFI system partition
+			"$scriptDir"InstallLog.sh "${targetVolume}" "Going to check the EFI system partition also."
+			# Unmount ALL mounted volumes named EFI. Returns 0=success, 1=fail
+			"$scriptDir"UnMountEFIvolumes.sh "${targetVolume}" "${scriptDir}"
+			returnValue=$?
+			if [ ${returnValue} = 0 ]; then
 				# Mount the EFI system partition
-				"$scriptDir"MountESP.sh "${targetDisk}" "${targetVolume}" "${scriptDir}"
+				"$scriptDir"MountESP.sh "${targetDisk}" "${targetVolume}" "${efiPartitionExist}" "${scriptDir}"
 			fi
-
-			# Check for another existing Chameleon installation on the same disk
-			"$scriptDir"CheckPreviousChameleon.sh "${targetDisk}" "${targetDeviceRaw}" "${targetDevice}" "${targetVolume}" "${scriptDir}"
 		fi
+		# Check for another existing Chameleon installation on the same disk
+		"$scriptDir"CheckPreviousChameleon.sh "${targetDisk}" "${targetDeviceRaw}" "${targetDevice}" "${targetVolume}" "${scriptDir}"
 
 		# Append a line break to the installer log
 		"$scriptDir"InstallLog.sh "${targetVolume}" "LineBreak"
